thanos:
  objstoreConfig: |-
    type: GCS
    config:
      bucket: synthos-thanos

  query:
    enabled: true
    replicaLabel: [prometheus_replica]

  storegateway:
    enabled: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: observabitliy-sa@idg-devops.iam.gserviceaccount.com

  bucketweb:
    enabled: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: observabitliy-sa@idg-devops.iam.gserviceaccount.com

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  compactor:
    enabled: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: observabitliy-sa@idg-devops.iam.gserviceaccount.com
    retentionResolutionRaw: 7d
    retentionResolution5m: 30d
    retentionResolution1h: 90d
    persistence:
      size: 30Gi 

