thanos:
  objstoreConfig: |-
    type: GCS
    config:
      bucket: synthos-thanos
  query:
    stores:
      # # devops-prometheus-vm
      - 34.123.80.93:9090

      # # stage
      # - prom.exammple.com:80
      # # preprod
      # - prom.exammple.com:80

    replicaLabel: [prometheus_replica]

    # ingress:
    #   enabled: true
    #   hostname: thanos.monitoring.example.com
    #   annotations:
    #     cert-manager.io/cluster-issuer: zerossl-dns
    #     traefik.ingress.kubernetes.io/router.tls: "true"
    #     traefik.ingress.kubernetes.io/router.entrypoints: websecure
    #     kubernetes.io/ingress.class: traefik-internal
    #   tls: true

  bucketweb:
    enabled: true
    # serviceAccount:
    #   annotations:
    #     iam.gke.io/gcp-service-account: observabitliy-sa@idg-devops.iam.gserviceaccount.com

  compactor:
    enabled: true
    retentionResolutionRaw: 7d
    retentionResolution5m: 30d
    retentionResolution1h: 90d
    persistence:
      size: 30Gi
    # serviceAccount:
    #   annotations:
    #     iam.gke.io/gcp-service-account: observabitliy-sa@idg-devops.iam.gserviceaccount.com

  storegateway:
    enabled: true
    # serviceAccount:
    #   annotations:
    #     iam.gke.io/gcp-service-account: observabitliy-sa@idg-devops.iam.gserviceaccount.com

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
