thanos:
  # Enable components
  query:
    enabled: true
  storegateway:
    enabled: true

  # Object storage configuration (not used in this example)
  objstoreConfig: ""

  # Query configuration
  query:
    frontend:
      replicaCount: 1

  # Store gateway configuration
  storegateway:
    selectors: