thanos:
  objstoreConfig: |-
    type: GCS
    config:
      bucket: synthos-thanos
      service_account_json_key: ""

  query:
    enabled: true
    replicaLabel: [prometheus_replica]

  storegateway:
    enabled: true

  bucketweb:
    enabled: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  compactor:
    enabled: true
    retentionResolutionRaw: 7d
    retentionResolution5m: 30d
    retentionResolution1h: 90d
    persistence:
      size: 30Gi 

