thanos:
  # objstoreConfig: |-
  #   type: GCS
  #   config:
  #     bucket: synthos-thanos
  #   replicaLabel: [prometheus_replica]
  objstoreConfig:
    type: FILESYSTEM
    config:
      directory: ""

  bucketweb:
    enabled: 
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: observabitliy-sa@idg-devops.iam.gserviceaccount.com

  compactor:
    enabled: true
    retentionResolutionRaw: 7d
    retentionResolution5m: 30d
    retentionResolution1h: 90d
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: observabitliy-sa@idg-devops.iam.gserviceaccount.com
    persistence:
      size: 30Gi

  storegateway:
    enabled: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: observabitliy-sa@idg-devops.iam.gserviceaccount.com

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
