apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          cluster: apps
  template:
    metadata:
      name: '{{name}}-istio-base'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: dev-infra
      source:
        chart: base
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: 1.16.0
        helm:
          releaseName: istio-base
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
          jsonPointers:
            - /webhooks/0/failurePolicy
