apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
spec:
  generators:
  - list:
      elements:
      - name: safi-stage-apps
        server: https://172.17.47.219:8081
        values:
          override: |
            pilot:
              autoscaleMin: 2
              replicaCount: 2
            global:
              priorityClassName: "critical"
      - name: safi-brave-applications
        server: https://172.21.32.16:8081
        values:
          override: |
            pilot:
              autoscaleMin: 2
              replicaCount: 2
            global:
              priorityClassName: "critical"
      - name: safi-tangled-applications
        server: https://172.22.32.14:8081
        values:
          override: |
            pilot:
              autoscaleMin: 2
              replicaCount: 2
            global:
              priorityClassName: "critical"
  template:
    metadata:
      name: '{{name}}-istiod'
    spec:
      project: dev-infra
      source:
        chart: istiod
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: 1.16.0
        helm:
          releaseName: istiod
          values: | 
              {{values.override}}
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
