apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promtail
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .  
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-promtail'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../../base/
    spec:
      project: dev-infra
      source:
        repoURL: 'https://github.com/SafiBank/SaFiMono.git'
        path: devops/argocd/environments/common/infra/promtail/overlays/{{name}}
        targetRevision: HEAD
        plugin:
          name: kustomize-argocd-vault-replacer
      destination:
        server: '{{server}}'
        namespace: safi-logging
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
