apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik-external
spec:
  generators:
  - list:
      elements:
      - name: safi-brave-tyk-a
        server: https://172.21.96.10:8081
        values:
          override: |
            deployment:
              replicas: 1
            podDisruptionBudget:
              enabled: true
              maxUnavailable: 1
            ingressClass:
              enabled: true
              isDefaultClass: true
            ingressRoute:
              dashboard:
                enabled: false
            providers:
              kubernetesIngress:
                ingressClass: traefik
                publishedService:
                  enabled: true
            ports:
              metrics:
                expose: true
            resources:
              requests:
                cpu: "100m"
                memory: "50Mi"
              limits:
                cpu: "300m"
                memory: "150Mi"
            metrics:
              prometheus:
                serviceMonitor:
                  relabelings:
                    - sourceLabels: [__meta_kubernetes_pod_node_name]
                      separator: ;
                      regex: ^(.*)$
                      targetLabel: nodename
                      replacement: $1
                      action: replace
                  jobLabel: traefik-external
                  scrapeInterval: 30s
                  scrapeTimeout: 5s
                  honorLabels: true
  template:
    metadata:
      name: '{{name}}-traefik-external'
    spec:
      project: dev-infra
      source:
        chart: traefik
        repoURL: https://helm.traefik.io/traefik
        targetRevision: 20.3.0
        helm:
          releaseName: traefik-external
          values: | 
              {{values.override}}
      destination:
        server: '{{server}}'
        namespace: traefik-external
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
