grafana:
  # serviceAccount:
  #   annotations:
  #     iam.gke.io/gcp-service-account: sa-bigquery@<project>gserviceaccount.com

# Whether to create test-related resources (default - true)
  testFramework:
    enabled: false

  resources:
    limits:
      cpu: 100m
      memory: 128Mi

# busybox init container
  initChownData:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  adminUser: admin
  adminPassword: D3V0P$monitoring
  
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus-Thanos
          type: prometheus
          url: http://thanos.monitoring.svc:9090
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.monitoring.svc:80
          jsonData:
            maxLines: 1000
            derivedFields:
              - datasourceUid: Tempo
                matcherRegex: \"trace_id\":\"(\w+)\"
                name: TraceID
                url: $${__value.raw}
        - name: Tempo
          type: tempo
          access: proxy
          url: http://tempo.monitoring.svc:3100
          basicAuth: false
          jsonData:
            serviceMap:
              datasourceUid: Prometheus
            nodeGraph:
              enabled: true

  grafana.ini:
    server:
      root_url: https://grafana.monitoring.example.com

# Enables the cluster wide search for dashboards and adds/updates/deletes them in grafana
  sidecar:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: monitoring
      provider:
        foldersFromFilesStructure: true

  extraVolumeMounts:
    - name: sre-dir
      mountPath: /tmp/dashboards/SRE
    - name: devops-dir
      mountPath: /tmp/dashboards/Devops

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'Devops'
          folder: 'Devops'
          type: file
          disableDeletion: false
          allowUiUpdates: false
          updateIntervalSeconds: 30
          options:
            path: /tmp/dashboards/Devops
        - name: 'SRE'
          folder: 'SRE'
          type: file
          disableDeletion: false
          allowUiUpdates: false
          updateIntervalSeconds: 30
          options:
            path: /tmp/dashboards/SRE