apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .  
spec:
  project: env-monitoring
  source:
    repoURL: repoURL: 'https://github.com/meshconnections/argocdtest.git'
    path: devops/monitoring
    targetRevision: HEAD
  destination:
    server: https://172.21.80.5:8081
    namespace: observability
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
