apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .  
spec:
  project: observability
  source:
    repoURL: 'https://github.com/meshconnections/argocdtest.git'
    path: devops/monitoring/thanos
    targetRevision: HEAD
  destination:
    server: 'https://35.239.16.55'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m