---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cronjob-runner
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cronjob-runner
subjects:
- kind: ServiceAccount
  name: cronjob-runner
  namespace: cronjob
roleRef:
  kind: ClusterRole
  name: cronjob-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-runner
  namespace: cronjob
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-failed-pods
  namespace: cronjob
spec:
  schedule: "0 0 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-runner
          containers:
          - name: kubectl-runner
            image: bitnami/kubectl:1.24.2
            command:
              - /bin/sh
              - -c
              - kubectl get pods --all-namespaces --field-selector 'status.phase==Failed' -o json | kubectl delete -f -
          restartPolicy: OnFailure
