apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: thanos-alert-rules
  namespace: monitoring
spec:
  groups:
  - name: thanos-compact
    rules:
    - alert: ThanosCompactMultipleRunning
      annotations:
        description: No more than one Thanos Compact instance should be running at once. There are {{$value}} instances running.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactmultiplerunning
        summary: Thanos Compact has multiple instances running.
      expr: sum by (job) (up{job=~".*thanos-tangled-compact.*"}) > 1
      for: 5m
      labels:
        severity: warning
    - alert: ThanosCompactHalted
      annotations:
        description: Thanos Compact {{$labels.job}} has failed to run and now is halted.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthalted
        summary: Thanos Compact has failed to run and is now halted.
      expr: thanos_compact_halted{job=~".*thanos-tangled-compact.*"} == 1
      for: 5m
      labels:
        severity: warning
    - alert: ThanosCompactHighCompactionFailures
      annotations:
        description: Thanos Compact {{$labels.job}} is failing to execute {{$value | humanize}}% of compactions.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthighcompactionfailures
        summary: Thanos Compact is failing to execute compactions.
      expr: |
        (
          sum by (job) (rate(thanos_compact_group_compactions_failures_total{job=~".*thanos-tangled-compact.*"}[5m]))
        /
          sum by (job) (rate(thanos_compact_group_compactions_total{job=~".*thanos-tangled-compact.*"}[5m]))
        * 100 > 5
        )
      for: 15m
      labels:
        severity: warning
    - alert: ThanosCompactBucketHighOperationFailures
      annotations:
        description: Thanos Compact {{$labels.job}} Bucket is failing to execute {{$value | humanize}}% of operations.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactbuckethighoperationfailures
        summary: Thanos Compact Bucket is having a high number of operation failures.
      expr: |
        (
          sum by (job) (rate(thanos_objstore_bucket_operation_failures_total{job=~".*thanos-tangled-compact.*"}[5m]))
        /
          sum by (job) (rate(thanos_objstore_bucket_operations_total{job=~".*thanos-tangled-compact.*"}[5m]))
        * 100 > 5
        )
      for: 15m
      labels:
        severity: warning
    - alert: ThanosCompactHasNotRun
      annotations:
        description: Thanos Compact {{$labels.job}} has not uploaded anything for 24 hours.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthasnotrun
        summary: Thanos Compact has not uploaded anything for last 24 hours.
      expr: (time() - max by (job) (max_over_time(thanos_objstore_bucket_last_successful_upload_time{job=~".*thanos-tangled-compact.*"}[24h]))) / 60 / 60 > 24
      labels:
        severity: warning
  - name: thanos-store
    rules:
    - alert: ThanosStoreGrpcErrorRate
      annotations:
        description: Thanos Store {{$labels.job}} is failing to handle {{$value | humanize}}% of requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosstoregrpcerrorrate
        summary: Thanos Store is failing to handle qrpcd requests.
      expr: |
        (
          sum by (job) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded", job=~".*thanos-tangled-store.*"}[5m]))
        /
          sum by (job) (rate(grpc_server_started_total{job=~".*thanos-tangled-store.*"}[5m]))
        * 100 > 5
        )
      for: 5m
      labels:
        severity: warning
    - alert: ThanosStoreSeriesGateLatencyHigh
      annotations:
        description: Thanos Store {{$labels.job}} has a 99th percentile latency of {{$value}} seconds for store series gate requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosstoreseriesgatelatencyhigh
        summary: Thanos Store has high latency for store series gate requests.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (rate(thanos_bucket_store_series_gate_duration_seconds_bucket{job=~".*thanos-tangled-store.*"}[5m]))) > 2
        and
          sum by (job) (rate(thanos_bucket_store_series_gate_duration_seconds_count{job=~".*thanos-tangled-store.*"}[5m])) > 0
        )
      for: 10m
      labels:
        severity: warning
    - alert: ThanosStoreBucketHighOperationFailures
      annotations:
        description: Thanos Store {{$labels.job}} Bucket is failing to execute {{$value | humanize}}% of operations.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosstorebuckethighoperationfailures
        summary: Thanos Store Bucket is failing to execute operations.
      expr: |
        (
          sum by (job) (rate(thanos_objstore_bucket_operation_failures_total{job=~".*thanos-tangled-store.*"}[5m]))
        /
          sum by (job) (rate(thanos_objstore_bucket_operations_total{job=~".*thanos-tangled-store.*"}[5m]))
        * 100 > 5
        )
      for: 15m
      labels:
        severity: warning
    - alert: ThanosStoreObjstoreOperationLatencyHigh
      annotations:
        description: Thanos Store {{$labels.job}} Bucket has a 99th percentile latency of {{$value}} seconds for the bucket operations.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosstoreobjstoreoperationlatencyhigh
        summary: Thanos Store is having high latency for bucket operations.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=~".*thanos-tangled-store.*"}[5m]))) > 2
        and
          sum by (job) (rate(thanos_objstore_bucket_operation_duration_seconds_count{job=~".*thanos-tangled-store.*"}[5m])) > 0
        )
      for: 10m
      labels:
        severity: warning
  - name: thanos-query
    rules:
    - alert: ThanosQueryHttpRequestQueryErrorRateHigh
      annotations:
        description: Thanos Query {{$labels.job}} is failing to handle {{$value | humanize}}% of "query" requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosqueryhttprequestqueryerrorratehigh
        summary: Thanos Query is failing to handle requests.
      expr: |
        (
          sum by (job) (rate(http_requests_total{code=~"5..", job=~".*thanos-tangled-query.*", handler="query"}[5m]))
        /
          sum by (job) (rate(http_requests_total{job=~".*thanos-tangled-query.*", handler="query"}[5m]))
        ) * 100 > 5
      for: 5m
      labels:
        severity: critical
    - alert: ThanosQueryHttpRequestQueryRangeErrorRateHigh
      annotations:
        description: Thanos Query {{$labels.job}} is failing to handle {{$value | humanize}}% of "query_range" requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosqueryhttprequestqueryrangeerrorratehigh
        summary: Thanos Query is failing to handle requests.
      expr: |
        (
          sum by (job) (rate(http_requests_total{code=~"5..", job=~".*thanos-tangled-query.*", handler="query_range"}[5m]))
        /
          sum by (job) (rate(http_requests_total{job=~".*thanos-tangled-query.*", handler="query_range"}[5m]))
        ) * 100 > 5
      for: 5m
      labels:
        severity: critical
    - alert: ThanosQueryGrpcServerErrorRate
      annotations:
        description: Thanos Query {{$labels.job}} is failing to handle {{$value | humanize}}% of requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosquerygrpcservererrorrate
        summary: Thanos Query is failing to handle requests.
      expr: |
        (
          sum by (job) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded", job=~".*thanos-tangled-query.*"}[5m]))
        /
          sum by (job) (rate(grpc_server_started_total{job=~".*thanos-tangled-query.*"}[5m]))
        * 100 > 5
        )
      for: 5m
      labels:
        severity: warning
    - alert: ThanosQueryGrpcClientErrorRate
      annotations:
        description: Thanos Query {{$labels.job}} is failing to send {{$value | humanize}}% of requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosquerygrpcclienterrorrate
        summary: Thanos Query is failing to send requests.
      expr: |
        (
          sum by (job) (rate(grpc_client_handled_total{grpc_code!="OK", job=~".*thanos-tangled-query.*"}[5m]))
        /
          sum by (job) (rate(grpc_client_started_total{job=~".*thanos-tangled-query.*"}[5m]))
        ) * 100 > 5
      for: 15m
      labels:
        severity: warning
    - alert: ThanosQueryHighDNSFailures
      annotations:
        description: Thanos Query {{$labels.job}} have {{$value | humanize}}% of failing DNS queries for store endpoints.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosqueryhighdnsfailures
        summary: Thanos Query is having high number of DNS failures.
      expr: |
        (
          sum by (job) (rate(thanos_query_store_apis_dns_failures_total{job=~".*thanos-tangled-query.*"}[5m]))
        /
          sum by (job) (rate(thanos_query_store_apis_dns_lookups_total{job=~".*thanos-tangled-query.*"}[5m]))
        ) * 100 > 1
      for: 15m
      labels:
        severity: warning
    - alert: ThanosQueryInstantLatencyHigh
      annotations:
        description: Thanos Query {{$labels.job}} has a 99th percentile latency of {{$value}} seconds for instant queries.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosqueryinstantlatencyhigh
        summary: Thanos Query has high latency for queries.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~".*thanos-tangled-query.*", handler="query"}[5m]))) > 40
        and
          sum by (job) (rate(http_request_duration_seconds_bucket{job=~".*thanos-tangled-query.*", handler="query"}[5m])) > 0
        )
      for: 10m
      labels:
        severity: critical
    - alert: ThanosQueryRangeLatencyHigh
      annotations:
        description: Thanos Query {{$labels.job}} has a 99th percentile latency of {{$value}} seconds for range queries.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosqueryrangelatencyhigh
        summary: Thanos Query has high latency for queries.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~".*thanos-tangled-query.*", handler="query_range"}[5m]))) > 90
        and
          sum by (job) (rate(http_request_duration_seconds_count{job=~".*thanos-tangled-query.*", handler="query_range"}[5m])) > 0
        )
      for: 10m
      labels:
        severity: critical
  - name: thanos-component-absent
    rules:
    - alert: ThanosCompactIsDown
      annotations:
        description: ThanosCompact has disappeared. Prometheus target for the component cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-tangled-compact.*"} == 1)
      for: 5m
      labels:
        severity: critical
    - alert: ThanosQueryIsDown
      annotations:
        description: ThanosQuery has disappeared. Prometheus target for the component cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosqueryisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-tangled-query.*"} == 1)
      for: 5m
      labels:
        severity: critical
    # - alert: ThanosReceiveIsDown
    #   annotations:
    #     description: ThanosReceive has disappeared. Prometheus target for the component cannot be discovered.
    #     runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceiveisdown
    #     summary: Thanos component has disappeared.
    #   expr: |
    #     absent(up{job=~".*thanos-tangled-receive.*"} == 1)
    #   for: 5m
    #   labels:
    #     severity: critical
    # - alert: ThanosRuleIsDown
    #   annotations:
    #     description: ThanosRule has disappeared. Prometheus target for the component cannot be discovered.
    #     runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosruleisdown
    #     summary: Thanos component has disappeared.
    #   expr: |
    #     absent(up{job=~".*thanos-tangled-rule.*"} == 1)
    #   for: 5m
    #   labels:
    #     severity: critical
    # - alert: ThanosSidecarIsDown
    #   annotations:
    #     description: ThanosSidecar has disappeared. Prometheus target for the component cannot be discovered.
    #     runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanossidecarisdown
    #     summary: Thanos component has disappeared.
    #   expr: |
    #     absent(up{job=~".*thanos-tangled-sidecar.*"} == 1)
    #   for: 5m
    #   labels:
    #     severity: critical
    - alert: ThanosStoreIsDown
      annotations:
        description: ThanosStore has disappeared. Prometheus target for the component cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosstoreisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-tangled-store.*"} == 1)
      for: 5m
      labels:
        severity: critical
