apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloudflare-exporter-rules
  namespace: monitoring
spec:
  groups:
  - name: cloudflare-exporter
    rules:
    # - alert: CloudflareHttp4xxErrorRate
    #   annotations:
    #     summary: Cloudflare http 4xx error rate (instance {{ $labels.instance }})
    #     description: "Cloudflare high HTTP 4xx error rate (> 10% for domain {{ $labels.zone }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    #   expr: (sum by(zone) (rate(cloudflare_zone_requests_status{status=~"^4.."}[15m])) / on (zone) sum by (zone) (rate(cloudflare_zone_requests_status[15m]))) * 100 > 10
    #   for: 10m
    #   labels:
    #     severity: warning
    # - alert: CloudflareHttp5xxErrorRate
    #   annotations:
    #     summary: Cloudflare http 5xx error rate (instance {{ $labels.instance }})
    #     description: "Cloudflare high HTTP 5xx error rate (> 10% for domain {{ $labels.zone }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    #   expr: (sum by (zone) (rate(cloudflare_zone_requests_status{status=~"^5.."}[5m])) / on (zone) sum by (zone) (rate(cloudflare_zone_requests_status[5m]))) * 100 > 10
    #   for: 0m
    #   labels:
    #     severity: critical
# Albania - AL,   Barbados - BB,  Burkina Faso - BF,  Cambodia - KH,  Cayman Islands - KY,  Gibraltar - GI,   Haiti     - HT
# Jamaica - JM,   Jordan   - JO,  Mali         - ML,  Morocco  - MA,  Myanmar        - MM,  Nicaragua - NI,   Pakistan  - PK
# Panama  - PA,   Senegal  - SN,  South Sudan  - SS,  Syria    - SY,  Turkiye        - TR,  Uganda    - UG,   UAE       - AE
# Yemen   - YE
# For more details refer https://safibank.atlassian.net/browse/DSUP-130
    - alert: CloudflareAMLGreylistCountry
      annotations:
        summary: Cloudflare GreyListCountry request more than 500 error rate (instance {{ $labels.instance }})
        description: "Cloudflare GreyListCountry request more than 500 error rate {{ $labels.zone }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      expr: sum by (country) (rate(cloudflare_zone_requests_status_country_host{country=~"AL|BB|BF|KH|KY|GI|HT|JM|JO|ML|MA|MM|NI|PK|PA|SN|SS|SY|TR|UG|AE|YE"}[1m])) * 60 > 500
      for: 0m
      labels:
        severity: info
    - alert: CloudflareAMLGreylistCountry
      annotations:
        summary: Cloudflare GreyListCountry request more than 1000 error rate (instance {{ $labels.instance }})
        description: "Cloudflare GreyListCountry request more than 500 error rate {{ $labels.zone }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      expr: sum by (country) (rate(cloudflare_zone_requests_status_country_host{country=~"SG|AL|BB|BF|KH|KY|GI|HT|JM|JO|ML|MA|MM|NI|PK|PA|SN|SS|SY|TR|UG|AE|YE"}[1m])) * 60 > 1000
      for: 0m
      labels:
        severity: warning
    - alert: CloudflareAMLGreylistCountry
      annotations:
        summary: Cloudflare GreyListCountry request more than 10000 error rate (instance {{ $labels.instance }})
        description: "Cloudflare GreyListCountry request more than 500 error rate {{ $labels.zone }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      expr: sum by (country) (rate(cloudflare_zone_requests_status_country_host{country=~"AL|BB|BF|KH|KY|GI|HT|JM|JO|ML|MA|MM|NI|PK|PA|SN|SS|SY|TR|UG|AE|YE"}[1m])) * 60 > 10000
      for: 0m
      labels:
        severity: critical
