apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@safibank.online
    privateKeySecretRef:
      name: letsencrypt-dns
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: safi-dns-safibankonline
