apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-dns
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: bC96iOYfnz6MHrdgR4iI_w
      keySecretRef:
        name: zerossl-eab
        key: secret
    privateKeySecretRef:
      name: zerossl-dns
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: safi-dns-safibankonline
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - smallog.tech
        - blueship.store
        - sfdvwork.xyz