cert-manager:
  installCRDs: true

  prometheus:
    servicemonitor:
      enabled: true

  serviceAccount:
    # Optional additional annotations to add to the controller's ServiceAccount
    annotations:
      iam.gke.io/gcp-service-account: safi-letsencrypt-zone-sa@safi-dns-safibankonline.iam.gserviceaccount.com
