tempo-distributed:
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: safi-tempo-gcs-brave@safi-env-brave-monitor.iam.gserviceaccount.com

  distributor:
    replicas: 3
    service:
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: h2c

  compactor:
    config:
      compaction:
        block_retention: 336h

  metricsGenerator:
    enabled: true
    replicas: 3
    config:
      storage:
        remote_write:
          - url: http://kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write

  server:
    grpc_server_max_recv_msg_size: 16777216
    grpc_server_max_send_msg_size: 16777216

  storage:
    trace:
      backend: gcs
      gcs:
        bucket_name: safi-tempo-brave

  serviceMonitor:
    enabled: true

  traces:
    otlp:
      http:
        enabled: true
      grpc:
        enabled: true

  search:
    enabled: true

  global_overrides:
    max_search_bytes_per_trace: 0
    metrics_generator_processors:
      - service-graphs
      - span-metrics

  minio:
    enabled: false
