---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: grafana
          path: devops/monitoring/grafana
          namespace: monitoring
          server: 'https://34.70.26.235'
        - name: grafana-dashboards
          path: devops/monitoring/grafana-dashboards
          namespace: monitoring
          server: 'https://34.70.26.235'
        - name: thanos
          path: devops/monitoring/thanos
          namespace: monitoring
          server: 'https://34.70.26.235'
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
    spec:
      project: observability
      source:
        repoURL: 'https://github.com/meshconnections/argocdtest.git'
        path: "{{path}}"
        targetRevision: HEAD
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
