apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-set
  namespace: argocd
spec:
  generators:
    - name: observability
      list:
        - name: grafana
          path: devops/monitoring/grafana
          namespace: monitoring
        - name: grafana-dash
          path: devops/monitoring/grafana-dashboards
          namespace: monitoring
  template:
    metadata:
      name: "{{name}}"
      namespace: "{{namespace}}"
    spec:
      project: observability
      source:
        repoURL: 'https://github.com/meshconnections/argocdtest.git'
        path: "{{path}}"
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m