---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: grafana
          path: devops/monitoring/grafana
          namespace: monitoring
        - name: grafana-dashboard
          path: devops/monitoring/grafana-dashboard
          namespace: monitoring
  template:
    metadata:
      name: "appset-{{name}}"
      namespace: argocd
    spec:
      project: observability
      source:
        repoURL: 'https://github.com/meshconnections/argocdtest.git'
        path: "{{path}}"
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'