apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-alert-rules
  namespace: monitoring
spec:
  groups:
  - name: argocd
    rules:
    # - alert: "ArgoCDAppOutOfSync"
    #   expr: argocd_app_info{sync_status="OutOfSync"} > 0
    #   annotations:
    #     summary: "ArgoCD Application is OutOfSync for longer than 12 hours"
    #     description: |-
    #       The application {{ $labels.name }} has not been synchronized for over
    #       12 hours which means that the state of this cloud has drifted away from the
    #       state inside Git.
    #   for: 12h
    #   labels:
    #     severity: critical
    - alert: "ArgoCDAppProgressing"
      expr: argocd_app_info{health_status="Progressing"} > 0
      annotations:
        summary: "ArgoCD Application Progressing longer than 10 minutes"
        description: |-
          ArgoCD Application {{ $labels.name }} Progressing longer than 10 minutes.
      for: 10m
      labels:
        severity: critical
    - alert: "ArgoCDAppUnknown"
      expr: argocd_app_info{health_status="Unknown"} > 0
      annotations:
        summary: "ArgoCD Application Unknown for 10 minutes"
        description: |-
          ArgoCD Application {{ $labels.name }} Unknown for 10 minutes.
      for: 10m
      labels:
        severity: critical
    # - alert: "ArgoCDAppMissing"
    #   expr: argocd_app_info{health_status="Missing"} > 0
    #   annotations:
    #     summary: "ArgoCD Application Missing for 5 minutes"
    #     description: |-
    #       ArgoCD Application {{ $labels.name }} Missing for 5 minutes.
    #   for: 5m
    #   labels:
    #     severity: critical
    - alert: "ArgoCDAppDegraded"
      expr: argocd_app_info{health_status="Degraded"} > 0
      annotations:
        summary: "ArgoCD Application Degraded for 5 minutes"
        description: |-
          ArgoCD Application {{ $labels.name }} Degraded for 5 minutes.
      for: 5m
      labels:
        severity: critical
